# Generated by Django 5.1.4 on 2024-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumPokerEstimationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(blank=True, to='ScrumPokerEstimationApp.joueur'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='mode',
            field=models.CharField(max_length=10),
        ),
    ]
