# Generated by Django 5.1.4 on 2024-12-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumPokerEstimationApp', '0002_alter_partie_code_alter_partie_joueurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='votes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='partie',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(to='ScrumPokerEstimationApp.joueur'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='mode',
            field=models.CharField(choices=[('strict', 'Strict'), ('moyenne', 'Moyenne')], max_length=10),
        ),
    ]
