# Generated by Django 5.1.4 on 2024-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumPokerEstimationApp', '0003_partie_votes_alter_partie_code_alter_partie_joueurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='date_debut_vote',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
